all:
  children:
    virtualbox:
      hosts:
        kali:
          ansible_password: kali
          ansible_user: kali
          ansible_host: 192.168.1.55

        centos:
          ansible_password: cocociscko
          ansible_user: root
          ansible_host: 192.168.1.103

        hote_ubuntu:
          ansible_password: " " 
          ansible_user: nabster
          ansible_host: 192.168.1.104


    prometheus:
      hosts:
        kali:



