apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-int-legacy-poc
spec:
  storageClassName: csi-s3
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: s3-mount-poc
    name: rustfs-pvc
  csi:
    driver: ru.yandex.s3.csi
    controllerPublishSecretRef:
      name: csi-s3-secret
      namespace: csi-s3-system
    nodePublishSecretRef:
      name: csi-s3-secret
      namespace: csi-s3-system
    nodeStageSecretRef:
      name: csi-s3-secret
      namespace: csi-s3-system
    volumeAttributes:
      capacity: 10Gi
      mounter: geesefs
      options: --memory-limit 1000 --dir-mode 0777 --file-mode 0666
    volumeHandle: k8s-int-legacy-poc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustfs-pvc
  namespace: s3-mount-poc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
