apiVersion: v1
kind: Pod
metadata:
  name: s3-mount-test
  namespace: s3-mount-poc
spec:
  containers:
    - name: test
      image: alpine:3.20
      command:
        - /bin/sh
        - -c
        - |
          echo "Pod démarré"
          sleep 3600
      volumeMounts:
        - name: s3-volume
          mountPath: /data
  volumes:
    - name: s3-volume
      persistentVolumeClaim:
        claimName: rustfs-pvc