prometheus_user: "prometheus"
prometheus_group: "prometheus"
prometheus_service_name: "prometheus"
prometheus_binary_name: "prometheus"
prometheus_archive_name: "prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
prometheus_extracted_dir: "prometheus-{{ prometheus_version }}.linux-amd64"
prometheus_repo_url: "https://github.com/prometheus/prometheus"
prometheus_release_path: "releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
prometheus_download_url: "{{ prometheus_repo_url }}/{{ prometheus_release_path }}"
