[proxmox]
devops-test ansible_host=192.168.1.102 ansible_user=ciscko ansible_password=ciscko
devsecops ansible_host=192.168.1.85 ansible_user=devops ansible_password=devops
rustfs-node ansible_host=192.168.1.124 ansible_user=ciscko ansible_password=devops
proxy-dns ansible_host=192.168.1.16 ansible_user=ciscko ansible_password=proxydns


[prometheus]
devops-test

[victoriametrics]
devsecops

[grafana]
devsecops

[rustfs]
rustfs-node

[ldap]
rustfs-node

[keycloak]
rustfs-node

[dns]
proxy-dns

[opentofu]
rustfs-node