apiVersion: v1
kind: Namespace
metadata:
  name: csi-s3-system
  labels:
    app.kubernetes.io/name: csi-s3
    app.kubernetes.io/part-of: rustfs-csi-poc
    environment: int-legacy
---
apiVersion: v1
kind: Namespace
metadata:
  name: s3-mount-poc
  labels:
    app.kubernetes.io/name: s3-mount-poc
    app.kubernetes.io/part-of: rustfs-csi-poc
    environment: int-legacy
