apiVersion: v1
kind: Pod
metadata:
  name: csi-s3-test-alpine
  namespace: s3-mount-poc
spec:
  containers:
    - name: alpine
      image: alpine:3.20
      command:
        - /bin/sh
        - -c
        - sleep 3600
      volumeMounts:
        - mountPath: /mnt/storage
          name: webroot

  volumes:
    - name: webroot
      persistentVolumeClaim:
        claimName: rustfs-pvc