---
- name: Install bind9 packages
  ansible.builtin.apt:
    name:
      - bind9
      - bind9utils
      - bind9-doc
      - dnsutils
    state: present
    update_cache: true

- name: Enable and start bind9
  ansible.builtin.systemd:
    name: named
    enabled: true
    state: started
