---
- name: Create VictoriaMetrics system group
  ansible.builtin.group:
    name: "{{ victoriametrics_system_group }}"
    state: present
    system: true
  when: victoriametrics_system_group != "root"

- name: Create VictoriaMetrics system user
  ansible.builtin.user:
    name: "{{ victoriametrics_system_user }}"
    group: "{{ victoriametrics_system_group }}"
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    state: present
  when: victoriametrics_system_user != "root"

- name: Ensure VictoriaMetrics install directory exists
  ansible.builtin.file:
    path: "{{ victoriametrics_install_dir }}"
    state: directory
    mode: "0755"

- name: Ensure VictoriaMetrics temporary directory exists
  ansible.builtin.file:
    path: "{{ victoriametrics_tmp_dir }}"
    state: directory
    mode: "0755"

- name: Ensure VictoriaMetrics storage directory exists
  ansible.builtin.file:
    path: "{{ victoriametrics_data_dir }}"
    state: directory
    owner: "{{ victoriametrics_system_user }}"
    group: "{{ victoriametrics_system_group }}"
    mode: "0750"

- name: Download and unarchive VictoriaMetrics single binary
  ansible.builtin.unarchive:
    src: "{{ victoriametrics_download_url }}"
    dest: "{{ victoriametrics_tmp_dir }}"
    remote_src: true
    extra_opts:
      - --no-same-owner
  when:
    - not ansible_check_mode

- name: Install VictoriaMetrics single binary
  ansible.builtin.copy:
    src: "{{ victoriametrics_tmp_dir }}/victoria-metrics-prod"
    dest: "{{ victoriametrics_install_dir }}/{{ victoriametrics_binary_name }}"
    owner: root
    group: root
    mode: "0755"
    remote_src: true
  notify: Restart VictoriaMetrics single

- name: Restore SELinux context for VictoriaMetrics binary
  ansible.builtin.command:
    cmd: "restorecon -v {{ victoriametrics_install_dir }}/{{ victoriametrics_binary_name }}"
  register: victoriametrics_restorecon
  changed_when: "'relabeled' in victoriametrics_restorecon.stdout"
  when:
    - ansible_facts['selinux'] is defined
    - ansible_facts['selinux'].status == "enabled"
    - not ansible_check_mode
